In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE

In [173]:
# Import data dari CSV
data = pd.read_csv('./testdataset.csv')
data.head(10)

,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,Sensor9,Sensor10,Kondisi
0,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Normal
1,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Less,Normal
2,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,More,Vandalisme
3,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Less,NoData,Normal
4,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,More,NoData,Vandalisme
5,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Less,Less,GempaTidakMerusak
6,NoData,NoData,NoData,NoData,NoData,NoData,NoData,NoData,More,More,GempaMerusak
7,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Less,NoData,NoData,Normal
8,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Less,NoData,Less,GempaTidakMerusak
9,NoData,NoData,NoData,NoData,NoData,NoData,NoData,Less,Less,NoData,GempaTidakMerusak

In [237]:
# Konversi tiap value kedalam bentuk angka
data.loc[data['Sensor1'] == 'NoData', 'Sensor1'] = 0
data.loc[data['Sensor1'] == 'Less', 'Sensor1'] = 1
data.loc[data['Sensor1'] == 'More', 'Sensor1'] = 2

data.loc[data['Sensor2'] == 'NoData', 'Sensor2'] = 0
data.loc[data['Sensor2'] == 'Less', 'Sensor2'] = 1
data.loc[data['Sensor2'] == 'More', 'Sensor2'] = 2

data.loc[data['Sensor3'] == 'NoData', 'Sensor3'] = 0
data.loc[data['Sensor3'] == 'Less', 'Sensor3'] = 1
data.loc[data['Sensor3'] == 'More', 'Sensor3'] = 2

data.loc[data['Sensor4'] == 'NoData', 'Sensor4'] = 0
data.loc[data['Sensor4'] == 'Less', 'Sensor4'] = 1
data.loc[data['Sensor4'] == 'More', 'Sensor4'] = 2

data.loc[data['Sensor5'] == 'NoData', 'Sensor5'] = 0
data.loc[data['Sensor5'] == 'Less', 'Sensor5'] = 1
data.loc[data['Sensor5'] == 'More', 'Sensor5'] = 2

data.loc[data['Sensor6'] == 'NoData', 'Sensor6'] = 0
data.loc[data['Sensor6'] == 'Less', 'Sensor6'] = 1
data.loc[data['Sensor6'] == 'More', 'Sensor6'] = 2

data.loc[data['Sensor7'] == 'NoData', 'Sensor7'] = 0
data.loc[data['Sensor7'] == 'Less', 'Sensor7'] = 1
data.loc[data['Sensor7'] == 'More', 'Sensor7'] = 2

data.loc[data['Sensor8'] == 'NoData', 'Sensor8'] = 0
data.loc[data['Sensor8'] == 'Less', 'Sensor8'] = 1
data.loc[data['Sensor8'] == 'More', 'Sensor8'] = 2

data.loc[data['Sensor9'] == 'NoData', 'Sensor9'] = 0
data.loc[data['Sensor9'] == 'Less', 'Sensor9'] = 1
data.loc[data['Sensor9'] == 'More', 'Sensor9'] = 2

data.loc[data['Sensor10'] == 'NoData', 'Sensor10'] = 0
data.loc[data['Sensor10'] == 'Less', 'Sensor10'] = 1
data.loc[data['Sensor10'] == 'More', 'Sensor10'] = 2

data.loc[data['Kondisi'] == 'Vandalisme', 'Kondisi'] = 2
data.loc[data['Kondisi'] == 'Normal', 'Kondisi'] = 0
data.loc[data['Kondisi'] == 'GempaTidakMerusak', 'Kondisi'] = 1
data.loc[data['Kondisi'] == 'GempaMerusak', 'Kondisi'] = 1

data = data.apply(pd.to_numeric, errors='coerce')
data.head(50)

,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,Sensor9,Sensor10,Kondisi
0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,2,2
3,0,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,2,0,2
5,0,0,0,0,0,0,0,0,1,1,1
6,0,0,0,0,0,0,0,0,2,2,1
7,0,0,0,0,0,0,0,1,0,0,0
8,0,0,0,0,0,0,0,1,0,1,1
9,0,0,0,0,0,0,0,1,1,0,1
10,0,0,0,0,0,0,0,1,1,1,1
11,0,0,0,0,0,0,0,1,1,2,1
12,0,0,0,0,0,0,0,1,2,1,1
13,0,0,0,0,0,0,0,1,2,2,1
14,0,0,0,0,0,0,0,2,0,0,2
15,0,0,0,0,0,0,0,2,0,2,1
16,0,0,0,0,0,0,0,2,2,0,1
17,0,0,0,0,0,0,0,2,1,1,1
18,0,0,0,0,0,0,0,2,1,2,1
19,0,0,0,0,0,0,0,2,2,1,1
20,0,0,0,0,0,0,0,2,2,2,1
21,0,0,0,0,0,0,1,0,0,0,0
22,0,0,0,0,0,0,1,0,0,1,1
23,0,0,0,0,0,0,1,0,1,0,1
24,0,0,0,0,0,0,1,0,1,1,1
25,0,0,0,0,0,0,1,0,1,2,1
26,0,0,0,0,0,0,1,0,2,1,1
27,0,0,0,0,0,0,1,0,2,2,1
28,0,0,0,0,0,0,1,1,0,0,1
29,0,0,0,0,0,0,1,1,0,1,1
30,0,0,0,0,0,0,1,1,0,2,1
31,0,0,0,0,0,0,1,1,1,0,1
32,0,0,0,0,0,0,1,1,2,0,1
33,0,0,0,0,0,0,1,1,1,1,1
34,0,0,0,0,0,0,1,1,1,2,1
35,0,0,0,0,0,0,1,1,2,1,1
36,0,0,0,0,0,0,1,1,2,2,1
37,0,0,0,0,0,0,1,2,0,1,1
38,0,0,0,0,0,0,1,2,0,2,1
39,0,0,0,0,0,0,1,2,1,0,1
40,0,0,0,0,0,0,1,2,2,0,1
41,0,0,0,0,0,0,1,2,1,1,1
42,0,0,0,0,0,0,1,2,1,2,1
43,0,0,0,0,0,0,1,2,2,1,1
44,0,0,0,0,0,0,1,2,2,2,1
45,0,0,0,0,0,0,2,0,0,0,2
46,0,0,0,0,0,0,2,0,0,2,1
47,0,0,0,0,0,0,2,0,2,0,1
48,0,0,0,0,0,0,2,0,1,1,1
49,0,0,0,0,0,0,2,0,1,2,1

In [175]:
X = data.iloc[:, 0:10].values  # Independent Feature
y = data.iloc[:, -1].values     # Dependent Feature
smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_resample(X,y)

In [176]:
from collections import Counter
print("Before SMOTE y_train :" , Counter(y))
print("After SMOTE y_train :" , Counter(y_train_smote))

Before SMOTE y_train : Counter({1: 58938, 0: 11, 2: 10})
After SMOTE y_train : Counter({0: 58938, 2: 58938, 1: 58938})

In [209]:
X_train, X_test, y_train, y_test = train_test_split(X_train_smote, y_train_smote, test_size = 0.1, random_state = 0)

In [210]:
# Membuat model Naive Bayes terhadap Training set
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [211]:
# Memprediksi hasil test set
y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, ..., 2, 0, 0], dtype=int64)

In [212]:
# Menghitung tingkat akurasi
accuracy_score(y_test, y_pred)

0.9992647890510123

In [213]:
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = model.fit(X_train, y_train)
nbtrain.class_count_

array([53105., 53129., 52898.])

In [214]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(X_test)
y_pred

array([1, 1, 0, ..., 2, 0, 0], dtype=int64)

In [215]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(X_test)

array([[0.00000000e+00, 1.00000000e+00, 4.90630844e-67],
       [0.00000000e+00, 1.00000000e+00, 9.57019886e-26],
       [1.00000000e+00, 9.69705662e-27, 3.87586372e-19],
       ...,
       [0.00000000e+00, 1.09693779e-06, 9.99998903e-01],
       [1.00000000e+00, 9.69705662e-27, 3.87586372e-19],
       [1.00000000e+00, 9.69705662e-27, 3.87586372e-19]])

In [216]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[5833,    0,    0],
       [   0, 5797,   12],
       [   0,    1, 6039]], dtype=int64)

In [217]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5833
           1       1.00      1.00      1.00      5809
           2       1.00      1.00      1.00      6040

    accuracy                           1.00     17682
   macro avg       1.00      1.00      1.00     17682
weighted avg       1.00      1.00      1.00     17682

In [218]:
# K-fold CV
scores = cross_val_score(nbtrain, X_train, y_train, scoring ='accuracy', cv =100)
scores

array([1.        , 1.        , 1.        , 0.99937186, 0.99937186,
       1.        , 0.99937186, 0.99937186, 0.99937186, 1.        ,
       0.99937186, 1.        , 0.99874372, 1.        , 1.        ,
       0.99937186, 1.        , 1.        , 0.99937186, 0.99874372,
       1.        , 0.99874372, 0.99937186, 0.99937186, 0.99937186,
       0.99874372, 0.99874372, 1.        , 1.        , 0.99874372,
       1.        , 1.        , 0.99937146, 1.        , 0.99937146,
       0.99937146, 0.99874293, 1.        , 0.99937146, 0.99937146,
       0.99937146, 0.99937146, 0.99937146, 1.        , 0.99811439,
       1.        , 0.99937146, 1.        , 1.        , 0.99937146,
       0.99937146, 1.        , 1.        , 1.        , 0.99874293,
       0.99937146, 0.99937146, 0.99874293, 1.        , 0.99937146,
       0.99874293, 0.99874293, 0.99937146, 0.99937146, 1.        ,
       1.        , 0.99748586, 0.99937146, 0.99937146, 0.99937146,
       0.99937146, 0.99748586, 1.        , 1.        , 0.99874293,
       1.        , 0.99874293, 1.        , 0.99811439, 0.99937146,
       1.        , 0.99937146, 1.        , 0.99937146, 0.99937146,
       1.        , 1.        , 1.        , 0.99937146, 1.        ,
       0.99937146, 1.        , 1.        , 1.        , 0.99937146,
       0.99937146, 0.99937146, 1.        , 0.99937146, 0.99937146])

In [219]:
#Printting the average score
print(np.mean(scores))

0.9994846916859594

In [220]:
model.fit(X_train_smote,y_train_smote)
y_predict = model.predict(X_train_smote)
print(accuracy_score(y_train_smote,y_predict))
pd.crosstab(y_train_smote,y_predict)

0.9994627122286697

col_0      0      1      2
row_0
0      58928      0     10
1          0  58858     80
2          0      5  58933

In [221]:
# testing_data = pd.read_csv('./testing_dataset.csv')
# testing_data.head()

In [222]:
# # Konversi tiap value kedalam bentuk numerik
# testing_data.loc[testing_data['Sensor1'] == 'no data', 'Sensor1'] = 0
# testing_data.loc[testing_data['Sensor1'] == 'less', 'Sensor1'] = 1
# testing_data.loc[testing_data['Sensor1'] == 'more', 'Sensor1'] = 2

# testing_data.loc[testing_data['Sensor2'] == 'no data', 'Sensor2'] = 0
# testing_data.loc[testing_data['Sensor2'] == 'less', 'Sensor2'] = 1
# testing_data.loc[testing_data['Sensor2'] == 'more', 'Sensor2'] = 2

# testing_data.loc[testing_data['Sensor3'] == 'no data', 'Sensor3'] = 0
# testing_data.loc[testing_data['Sensor3'] == 'less', 'Sensor3'] = 1
# testing_data.loc[testing_data['Sensor3'] == 'more', 'Sensor3'] = 2

# testing_data.loc[testing_data['Sensor4'] == 'no data', 'Sensor4'] = 0
# testing_data.loc[testing_data['Sensor4'] == 'less', 'Sensor4'] = 1
# testing_data.loc[testing_data['Sensor4'] == 'more', 'Sensor4'] = 2

# testing_data.loc[testing_data['Sensor5'] == 'no data', 'Sensor5'] = 0
# testing_data.loc[testing_data['Sensor5'] == 'less', 'Sensor5'] = 1
# testing_data.loc[testing_data['Sensor5'] == 'more', 'Sensor5'] = 2

# testing_data.loc[testing_data['Sensor6'] == 'no data', 'Sensor6'] = 0
# testing_data.loc[testing_data['Sensor6'] == 'less', 'Sensor6'] = 1
# testing_data.loc[testing_data['Sensor6'] == 'more', 'Sensor6'] = 2

# testing_data.loc[testing_data['Sensor7'] == 'no data', 'Sensor7'] = 0
# testing_data.loc[testing_data['Sensor7'] == 'less', 'Sensor7'] = 1
# testing_data.loc[testing_data['Sensor7'] == 'more', 'Sensor7'] = 2

# testing_data.loc[testing_data['Sensor8'] == 'no data', 'Sensor8'] = 0
# testing_data.loc[testing_data['Sensor8'] == 'less', 'Sensor8'] = 1
# testing_data.loc[testing_data['Sensor8'] == 'more', 'Sensor8'] = 2

# testing_data.loc[testing_data['Sensor9'] == 'no data', 'Sensor9'] = 0
# testing_data.loc[testing_data['Sensor9'] == 'less', 'Sensor9'] = 1
# testing_data.loc[testing_data['Sensor9'] == 'more', 'Sensor9'] = 2

# testing_data.loc[testing_data['Sensor10'] == 'no data', 'Sensor10'] = 0
# testing_data.loc[testing_data['Sensor10'] == 'less', 'Sensor10'] = 1
# testing_data.loc[testing_data['Sensor10'] == 'more', 'Sensor10'] = 2


# testing_data = testing_data.apply(pd.to_numeric, errors='coerce')
# testing_data.head()

In [235]:
testing_data_X = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1]

In [236]:
testing_pred = model.predict([testing_data_X])
testing_pred

array([1], dtype=int64)